### ISSUE TITLE
我现在想要做Pagination，做出来是有了但是没有效果是什么问题，想知道dots和active如何绑值才能让Pagination动起来

### ISSUE THREAD

**Issue by x1098410620** [helicopters/wc-swiper#1]

**Comment by helicopters** [comment]
@x1098410620 hi, 在每次 slide 滑动结束之后, 会触发一个 transitionend 事件（在 wc-swiper 上监听）, 可以在这个事件里面, 拿到 当前所在的 slide 的索引值. 将这个索引值传递给你所定义的 pagination(你的 pagintation 需要设置一个 props 属性来接收索引),  你自定义的  pagination 中, 通过传递过来的索引值, 切换不同的 class 即可.

**Comment by x1098410620** [comment]
this.$refs.swiper.currentSlide  通过这个方法拿到的值好像有问题啊，不能用啊，这个是什么问题呢？还有如果要是打印这个值的话，你那个方法第一张和第二张返回的都是1，用计算属性来监听的话这个currentSlide值未定义啊

**Comment by helicopters** [comment]
@x1098410620  我并没有在  API 里面暴露出 this.$refs.swiper.currentSlide 这个属性哈, 我刚才看了下我的demo, 你可以参考这个样子实现: https://github.com/helicopters/wc-swiper/blob/master/src/App.vue.

**Comment by x1098410620** [comment]
这样可以还有最后一个问题，就是收到的值永远都是从1开始，第一张和第二章都是1，还有你那个wcSwiper.vue中的transitionend 这个函数里面有个bug   currentSlide的值要转换成整行，不然判断失效，而且那个this.slidesNumber是减二  不是减一   减一就会断掉所以希望优化。

**Comment by helicopters** [comment]
@x1098410620  好的，我下班看下.
