### ISSUE TITLE
轮播回调事件问题

### ISSUE THREAD

**Issue by Ace7523** [helicopters/wc-swiper#4]
<wc-slide v-for="(v, k) in list" :key="k" :class="map[k]">
          
          <div :class="{ns:imageFlag % 2}">{{imageFlag % 2}}</div>

</wc-slide>
--------------------------------------------------------------------------------------
 transitionend (current) {
      this.imageFlag = current;
}
--------------------------------------------------------------------------------------

本意想在每次轮播结束后改变下样式，但是在最后一次回调时候，会闪一下，所以没办法加回调了，
大佬看看这问题呗

**Comment by helicopters** [comment]
@Ace7523 不好意思哈, 我没太理解你说的是什么意思, 能具体描述下吗.

**Comment by Ace7523** [comment]
留个微信好了，这个我打字也说不好，就是轮播插件有bug呢。。。绑定回调事件，最后一次的回调就有异常。    我微信  ：  Ace7523
